name: SDK Test

on:
  push:
    branches: [ "main", "6-ci-cd" ]
  pull_request:
    branches: [ "main", "6-ci-cd" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
  
    - name: Start tests
      run: vendor/bin/phpunit
      # TODO: add env