name: PHP Composer

on:
  push:
    branches: [ "main", "6-ci-cd" ]
  pull_request:
    branches: [ "main", "6-ci-cd" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Validate composer.json and composer.lock
    #   run: ls -l

    # - name: Cache Composer packages
    #   id: composer-cache
    #   uses: actions/cache@v3
    #   with:
    #     path: vendor
    #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-php-
    - name: update
      run: apt update
    - name: install php
      run: apt install php8.3
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
  
    - name: testing
      run: vendor/bin/phpunit

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
