name: SDK Test

on:
  push:
    branches: [ "main", "6-ci-cd" ]
  pull_request:
    branches: [ "main", "6-ci-cd" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Set env
      run: echo "TOKEN=${{ secrets.TOKEN }}\n" >> .env; echo "RIGHT_PRIVATE_KEY=\"${{ secrets.RIGHT_PRIVATE_KEY }}\"" >> .env;echo "WRONG_PRIVATE_KEY=\"${{ secrets.WRONG_PRIVATE_KEY }}\"" >> .env;

    - name: Start tests
      run: vendor/bin/phpunit
      env:
        TOKEN: "${{ secrets.TOKEN }}"
        RIGHT_PRIVATE_KEY: "${{ secrets.RIGHT_PRIVATE_KEY }}"
        WRONG_PRIVATE_KEY: "${{ secrets.WRONG_PRIVATE_KEY }}"
        